version: 2

project_name: dotfiles-manager
builds:
  - id: linux
    main: ./cmd/dotfiles-manager
    binary: dotfiles-manager
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/shpoont/dotfiles-manager/internal/app.buildVersion={{ .Version }}
  - id: darwin
    main: ./cmd/dotfiles-manager
    binary: dotfiles-manager
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/shpoont/dotfiles-manager/internal/app.buildVersion={{ .Version }}
archives:
  - id: default
    ids:
      - linux
      - darwin
    formats:
      - tar.gz
    files:
      - README.md
      - docs/**
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
