project_name: dotfiles-manager
builds:
  - id: linux
    main: .
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
  - id: darwin
    main: .
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - id: default
    builds:
      - linux
      - darwin
    format: tar.gz
    files:
      - README.md
      - docs/**
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
